// frontend/src/components/Telephony/Extensions.jsx
import React, { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { extensionsService } from '../../services/telephonyService'
import './Extensions.css'

const Extensions = () => {
  const [showModal, setShowModal] = useState(false)
  const queryClient = useQueryClient()

  const [formData, setFormData] = useState({
    extension: '',
    name: '',
    extension_type: 'SIP',
    secret: '',
    context: 'from-internal',
    callerid: '',
    email: '',
    voicemail_enabled: false,
  })

  // Query para obtener extensiones
  const { data: extensions = [], isLoading, error } = useQuery({
    queryKey: ['extensions'],
    queryFn: async () => {
      const response = await extensionsService.getAll()
      // Asegurar que siempre devuelve un array
      return Array.isArray(response.data) ? response.data : []
    },
  })

  // Mutation para crear extensión
  const createMutation = useMutation({
    mutationFn: extensionsService.create,
    onSuccess: () => {
      queryClient.invalidateQueries(['extensions'])
      toast.success('Extensión creada exitosamente')
      setShowModal(false)
      setFormData({
        extension: '',
        name: '',
        extension_type: 'SIP',
        secret: '',
        context: 'from-internal',
        callerid: '',
        email: '',
        voicemail_enabled: false,
      })
    },
    onError: (error) => {
      toast.error(error.response?.data?.message || 'Error al crear extensión')
    },
  })

  // Mutation para eliminar extensión
  const deleteMutation = useMutation({
    mutationFn: extensionsService.delete,
    onSuccess: () => {
      queryClient.invalidateQueries(['extensions'])
      toast.success('Extensión eliminada')
    },
    onError: () => {
      toast.error('Error al eliminar extensión')
    },
  })

  const handleSubmit = (e) => {
    e.preventDefault()
    createMutation.mutate(formData)
  }

  const handleDelete = (id) => {
    if (window.confirm('¿Está seguro de eliminar esta extensión?')) {
      deleteMutation.mutate(id)
    }
  }

  if (isLoading) return <div className="extensions-container"><p>Cargando...</p></div>
  if (error) return <div className="extensions-container"><p>Error al cargar extensiones</p></div>

  return (
    <div className="extensions-container">
      <div className="page-header">
        <h1>Extensiones</h1>
        <button className="btn-primary" onClick={() => setShowModal(true)}>
          + Nueva Extensión
        </button>
      </div>

      <div className="table-container">
        <table>
          <thead>
            <tr>
              <th>Extensión</th>
              <th>Nombre</th>
              <th>Tipo</th>
              <th>Contexto</th>
              <th>Estado</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {extensions.length === 0 ? (
              <tr>
                <td colSpan="6" className="no-data">No hay extensiones configuradas</td>
              </tr>
            ) : (
              extensions.map((ext) => (
                <tr key={ext.id}>
                  <td><strong>{ext.extension}</strong></td>
                  <td>{ext.name}</td>
                  <td>{ext.extension_type}</td>
                  <td>{ext.context}</td>
                  <td>
                    <span className={`status-badge ${ext.status === 'Activo' ? 'active' : 'inactive'}`}>
                      {ext.status}
                    </span>
                  </td>
                  <td>
                    <button className="btn-icon" title="Editar">✏️</button>
                    <button className="btn-icon" title="Eliminar" onClick={() => handleDelete(ext.id)}>🗑️</button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Nueva Extensión</h2>
              <button className="close-btn" onClick={() => setShowModal(false)}>×</button>
            </div>
            <form onSubmit={handleSubmit} className="modal-body">
              <div className="form-row">
                <div className="form-group">
                  <label>Extensión *</label>
                  <input
                    type="text"
                    value={formData.extension}
                    onChange={(e) => setFormData({ ...formData, extension: e.target.value })}
                    placeholder="1001"
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Nombre *</label>
                  <input
                    type="text"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    placeholder="Juan Pérez"
                    required
                  />
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Tipo</label>
                  <select
                    value={formData.extension_type}
                    onChange={(e) => setFormData({ ...formData, extension_type: e.target.value })}
                  >
                    <option value="SIP">SIP</option>
                    <option value="IAX2">IAX2</option>
                    <option value="PJSIP">PJSIP</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Contraseña *</label>
                  <input
                    type="password"
                    value={formData.secret}
                    onChange={(e) => setFormData({ ...formData, secret: e.target.value })}
                    placeholder="********"
                    required
                  />
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Contexto</label>
                  <select
                    value={formData.context}
                    onChange={(e) => setFormData({ ...formData, context: e.target.value })}
                  >
                    <option value="from-internal">from-internal</option>
                    <option value="from-external">from-external</option>
                    <option value="custom">custom</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Caller ID</label>
                  <input
                    type="text"
                    value={formData.callerid}
                    onChange={(e) => setFormData({ ...formData, callerid: e.target.value })}
                    placeholder='"Juan Pérez" <1001>'
                  />
                </div>
              </div>

              <div className="form-group">
                <label>Email (para notificaciones de buzón)</label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="usuario@ejemplo.com"
                />
              </div>

              <div className="form-group">
                <label className="checkbox-label">
                  <input
                    type="checkbox"
                    checked={formData.voicemail_enabled}
                    onChange={(e) => setFormData({ ...formData, voicemail_enabled: e.target.checked })}
                  />
                  <span>Habilitar buzón de voz</span>
                </label>
              </div>

              <div className="form-actions">
                <button type="button" className="btn-secondary" onClick={() => setShowModal(false)}>
                  Cancelar
                </button>
                <button type="submit" className="btn-primary" disabled={createMutation.isPending}>
                  {createMutation.isPending ? 'Creando...' : 'Crear Extensión'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

export default Extensions

// frontend/pages/extensions/index.vue
<template>
  <div class="space-y-6">
    <div class="flex justify-between items-center">
      <h1 class="text-3xl font-bold">Extensiones</h1>
      <div class="flex gap-2">
        <UButton
          v-if="error"
          icon="i-heroicons-arrow-path"
          @click="loadExtensions"
          :loading="loading"
        >
          Reintentar
        </UButton>
        <UButton
          icon="i-heroicons-plus"
          color="primary"
          @click="openCreateModal"
          :disabled="loading"
        >
          Agregar Extensión
        </UButton>
      </div>
    </div>

    <!-- Estado de carga/error -->
    <UAlert v-if="error" color="red" icon="i-heroicons-exclamation-triangle">
      {{ error }}
    </UAlert>

    <UCard v-if="loading" class="flex justify-center items-center py-12">
      <div class="text-center space-y-2">
        <UIcon name="i-heroicons-arrow-path" class="w-8 h-8 animate-spin mx-auto" />
        <p class="text-gray-500">Cargando extensiones...</p>
      </div>
    </UCard>

    <!-- Filtros -->
    <UCard v-if="!loading" class="divide-y">
      <template #header>
        <div class="flex gap-2">
          <UInput
            v-model="searchQuery"
            placeholder="Buscar por extensión o nombre..."
            icon="i-heroicons-magnifying-glass"
          />
          <USelect
            v-model="extensionFilter"
            :options="[
              { label: 'Todos', value: null },
              { label: 'SIP', value: 'SIP' },
              { label: 'IAX2', value: 'IAX2' },
              { label: 'PJSIP', value: 'PJSIP' }
            ]"
            option-attribute="label"
            value-attribute="value"
            placeholder="Filtrar por tipo"
          />
          <USelect
            v-model="statusFilter"
            :options="[
              { label: 'Todos', value: null },
              { label: 'Activas', value: true },
              { label: 'Inactivas', value: false }
            ]"
            option-attribute="label"
            value-attribute="value"
            placeholder="Filtrar por estado"
          />
        </div>
      </template>

      <!-- Tabla -->
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-gray-50 dark:bg-gray-900">
            <tr>
              <th class="px-4 py-3 text-left font-semibold">Extensión</th>
              <th class="px-4 py-3 text-left font-semibold">Nombre</th>
              <th class="px-4 py-3 text-left font-semibold">Tipo</th>
              <th class="px-4 py-3 text-left font-semibold">Email</th>
              <th class="px-4 py-3 text-left font-semibold">Buzón</th>
              <th class="px-4 py-3 text-left font-semibold">Estado</th>
              <th class="px-4 py-3 text-center font-semibold">Acciones</th>
            </tr>
          </thead>
          <tbody class="divide-y">
            <tr v-for="ext in filteredExtensions" :key="ext.id" class="hover:bg-gray-50 dark:hover:bg-gray-800">
              <td class="px-4 py-3 font-mono font-semibold">{{ ext.extension }}</td>
              <td class="px-4 py-3">{{ ext.name }}</td>
              <td class="px-4 py-3">
                <UBadge color="blue" variant="subtle">{{ ext.extension_type }}</UBadge>
              </td>
              <td class="px-4 py-3 text-xs">{{ ext.email || '-' }}</td>
              <td class="px-4 py-3">
                <UBadge v-if="ext.voicemail_enabled" color="green" variant="subtle">Habilitado</UBadge>
                <span v-else class="text-gray-500">-</span>
              </td>
              <td class="px-4 py-3">
                <UBadge :color="ext.is_active ? 'green' : 'gray'" variant="subtle">
                  {{ ext.is_active ? 'Activa' : 'Inactiva' }}
                </UBadge>
              </td>
              <td class="px-4 py-3 text-center">
                <UButton
                  variant="ghost"
                  icon="i-heroicons-pencil"
                  size="sm"
                  @click="editExtension(ext)"
                />
                <UButton
                  variant="ghost"
                  icon="i-heroicons-trash"
                  color="red"
                  size="sm"
                  @click="deleteExtension(ext.id)"
                />
              </td>
            </tr>
            <tr v-if="filteredExtensions.length === 0 && !loading">
              <td colspan="7" class="px-4 py-8 text-center text-gray-500">
                No hay extensiones configuradas
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </UCard>

    <!-- Modal crear/editar -->
    <USlideover v-model="isModalOpen" title="Extensión" @close="resetForm">
      <div class="p-4 space-y-4">
        <UFormGroup label="Extensión">
          <UInput v-model="form.extension" placeholder="Ej: 100" />
        </UFormGroup>

        <UFormGroup label="Nombre">
          <UInput v-model="form.name" placeholder="Ej: Juan Pérez" />
        </UFormGroup>

        <UFormGroup label="Tipo de Extensión">
          <USelect
            v-model="form.extension_type"
            :options="['SIP', 'IAX2', 'PJSIP']"
          />
        </UFormGroup>

        <UFormGroup label="Contraseña">
          <UInput v-model="form.secret" type="password" placeholder="Contraseña segura" />
        </UFormGroup>

        <UFormGroup label="Contexto">
          <USelect
            v-model="form.context"
            :options="[
              { label: 'from-internal', value: 'from-internal' },
              { label: 'from-external', value: 'from-external' },
              { label: 'custom', value: 'custom' }
            ]"
            option-attribute="label"
            value-attribute="value"
          />
        </UFormGroup>

        <UFormGroup label="Caller ID">
          <UInput v-model="form.callerid" placeholder="Ej: 100 <2001234567>" />
        </UFormGroup>

        <UFormGroup label="Email">
          <UInput v-model="form.email" type="email" placeholder="usuario@example.com" />
        </UFormGroup>

        <UFormGroup>
          <UCheckbox v-model="form.voicemail_enabled" label="Habilitar Buzón de Voz" />
        </UFormGroup>

        <UFormGroup>
          <UCheckbox v-model="form.is_active" label="Activada" />
        </UFormGroup>

        <div class="flex gap-2 pt-4">
          <UButton color="primary" @click="saveExtension" :loading="isSaving">
            Guardar
          </UButton>
          <UButton color="gray" @click="isModalOpen = false">
            Cancelar
          </UButton>
        </div>
      </div>
    </USlideover>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

interface Extension {
  id: number
  extension: string
  name: string
  extension_type: string
  secret: string
  context: string
  callerid: string
  email: string
  voicemail_enabled: boolean
  is_active: boolean
}

const extensions = ref<Extension[]>([])
const loading = ref(false)
const error = ref<string | null>(null)
const searchQuery = ref('')
const extensionFilter = ref<string | null>(null)
const statusFilter = ref<boolean | null>(null)
const isModalOpen = ref(false)
const isSaving = ref(false)
const editingId = ref<number | null>(null)

const { apiFetch } = useApi()

const form = ref({
  extension: '',
  name: '',
  extension_type: 'SIP',
  secret: '',
  context: 'from-internal',
  callerid: '',
  email: '',
  voicemail_enabled: false,
  is_active: true
})

const filteredExtensions = computed(() => {
  return extensions.value.filter(ext => {
    const matchesSearch =
      ext.extension.includes(searchQuery.value) ||
      ext.name.toLowerCase().includes(searchQuery.value.toLowerCase())
    const matchesType = extensionFilter.value === null || ext.extension_type === extensionFilter.value
    const matchesStatus = statusFilter.value === null || ext.is_active === statusFilter.value
    return matchesSearch && matchesType && matchesStatus
  })
})

const openCreateModal = () => {
  resetForm()
  isModalOpen.value = true
}

const editExtension = (ext: Extension) => {
  form.value = { ...ext }
  editingId.value = ext.id
  isModalOpen.value = true
}

const loadExtensions = async () => {
  loading.value = true
  error.value = null
  const { data, error: fetchError } = await apiFetch<any>('/telephony/extensions/')
  if (fetchError.value) {
    error.value = 'Error al cargar las extensiones'
    console.error('Error loading extensions:', fetchError.value)
  } else {
    const raw = data.value
    extensions.value = Array.isArray(raw) ? raw : (raw?.results || [])
  }
  loading.value = false
}

const saveExtension = async () => {
  isSaving.value = true
  error.value = null
  try {
    if (editingId.value) {
      const { error: saveError } = await apiFetch(`/telephony/extensions/${editingId.value}/`, {
        method: 'PUT',
        body: form.value
      })
      if (saveError.value) throw new Error('Error al guardar la extensión')
    } else {
      const { error: saveError } = await apiFetch('/telephony/extensions/', {
        method: 'POST',
        body: form.value
      })
      if (saveError.value) throw new Error('Error al guardar la extensión')
    }
    await loadExtensions()
    isModalOpen.value = false
  } catch (err) {
    error.value = 'Error al guardar la extensión'
    console.error('Error saving extension:', err)
  } finally {
    isSaving.value = false
  }
}

const deleteExtension = async (id: number) => {
  if (confirm('¿Estás seguro de que deseas eliminar esta extensión?')) {
    try {
      const { error: delError } = await apiFetch(`/telephony/extensions/${id}/`, { method: 'DELETE' })
      if (delError.value) throw new Error('Error al eliminar la extensión')
      await loadExtensions()
    } catch (err) {
      error.value = 'Error al eliminar la extensión'
      console.error('Error deleting extension:', err)
    }
  }
}

const resetForm = () => {
  form.value = {
    extension: '',
    name: '',
    extension_type: 'SIP',
    secret: '',
    context: 'from-internal',
    callerid: '',
    email: '',
    voicemail_enabled: false,
    is_active: true
  }
  editingId.value = null
}

onMounted(() => loadExtensions())
</script>
