// frontend/src/components/Telephony/InboundRoutes.jsx
import React, { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { inboundRoutesService } from '../../services/telephonyService'
import './InboundRoutes.css'

const InboundRoutes = () => {
  const [showModal, setShowModal] = useState(false)
  const [editingId, setEditingId] = useState(null)
  const queryClient = useQueryClient()

  const [formData, setFormData] = useState({
    did: '',
    description: '',
    destination_type: 'ivr',
    destination: '',
    priority: 1,
    time_condition: '',
  })

  // Query para obtener rutas
  const { data: routes = [], isLoading } = useQuery({
    queryKey: ['inbound-routes'],
    queryFn: async () => {
      const response = await inboundRoutesService.getAll()
      const data = response.data?.results || response.data
      return Array.isArray(data) ? data : []
    },
  })

  // Mutation para crear
  const createMutation = useMutation({
    mutationFn: inboundRoutesService.create,
    onSuccess: () => {
      queryClient.invalidateQueries(['inbound-routes'])
      toast.success('Ruta creada exitosamente')
      resetForm()
    },
    onError: () => toast.error('Error al crear ruta'),
  })

  // Mutation para actualizar
  const updateMutation = useMutation({
    mutationFn: ({ id, data }) => inboundRoutesService.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries(['inbound-routes'])
      toast.success('Ruta actualizada exitosamente')
      resetForm()
    },
    onError: () => toast.error('Error al actualizar ruta'),
  })

  // Mutation para eliminar
  const deleteMutation = useMutation({
    mutationFn: inboundRoutesService.delete,
    onSuccess: () => {
      queryClient.invalidateQueries(['inbound-routes'])
      toast.success('Ruta eliminada')
    },
    onError: () => toast.error('Error al eliminar ruta'),
  })

  const resetForm = () => {
    setShowModal(false)
    setEditingId(null)
    setFormData({
      did: '',
      description: '',
      destination_type: 'ivr',
      destination: '',
      priority: 1,
      time_condition: '',
    })
  }

  const handleEdit = (route) => {
    setEditingId(route.id)
    setFormData({
      did: route.did,
      description: route.description,
      destination_type: route.destination_type,
      destination: route.destination,
      priority: route.priority,
      time_condition: route.time_condition || '',
    })
    setShowModal(true)
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    if (editingId) {
      updateMutation.mutate({ id: editingId, data: formData })
    } else {
      createMutation.mutate(formData)
    }
  }

  const handleDelete = (id) => {
    if (window.confirm('¿Está seguro de eliminar esta ruta?')) {
      deleteMutation.mutate(id)
    }
  }

  if (isLoading) return <div className="inbound-routes-container"><p>Cargando...</p></div>

  return (
    <div className="inbound-routes-container">
      <div className="page-header">
        <h1>Rutas Entrantes</h1>
        <button className="btn-primary" onClick={() => setShowModal(true)}>
          + Nueva Ruta
        </button>
      </div>

      <div className="table-container">
        <table>
          <thead>
            <tr>
              <th>DID / Número</th>
              <th>Descripción</th>
              <th>Destino</th>
              <th>Prioridad</th>
              <th>Estado</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {routes.length === 0 ? (
              <tr>
                <td colSpan="6" className="no-data">No hay rutas entrantes configuradas</td>
              </tr>
            ) : (
              routes.map((route) => (
                <tr key={route.id}>
                  <td><strong>{route.did}</strong></td>
                  <td>{route.description}</td>
                  <td>{route.destination}</td>
                  <td>{route.priority}</td>
                  <td>
                    <span className={`status-badge ${route.status === 'Activo' ? 'active' : 'inactive'}`}>
                      {route.status}
                    </span>
                  </td>
                  <td>
                    <button className="btn-icon" title="Editar" onClick={() => handleEdit(route)}>✏️</button>
                    <button className="btn-icon" title="Eliminar" onClick={() => handleDelete(route.id)}>🗑️</button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {showModal && (
        <div className="modal-overlay" onClick={resetForm}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>{editingId ? 'Editar' : 'Nueva'} Ruta Entrante</h2>
              <button className="close-btn" onClick={resetForm}>×</button>
            </div>
            <form onSubmit={handleSubmit} className="modal-body">
              <div className="form-row">
                <div className="form-group">
                  <label>DID / Número Entrante *</label>
                  <input
                    type="text"
                    value={formData.did}
                    onChange={(e) => setFormData({ ...formData, did: e.target.value })}
                    placeholder="3001234567"
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Descripción *</label>
                  <input
                    type="text"
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    placeholder="Línea Principal"
                    required
                  />
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Tipo de Destino</label>
                  <select
                    value={formData.destination_type}
                    onChange={(e) => setFormData({ ...formData, destination_type: e.target.value })}
                  >
                    <option value="ivr">IVR</option>
                    <option value="queue">Cola</option>
                    <option value="extension">Extensión</option>
                    <option value="voicemail">Buzón de Voz</option>
                    <option value="announcement">Anuncio</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Destino *</label>
                  <input
                    type="text"
                    value={formData.destination}
                    onChange={(e) => setFormData({ ...formData, destination: e.target.value })}
                    placeholder="Seleccione o ingrese destino"
                    required
                  />
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Prioridad</label>
                  <input
                    type="number"
                    value={formData.priority}
                    onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
                    min="1"
                    max="99"
                  />
                </div>
                <div className="form-group">
                  <label>Condición de Horario</label>
                  <select
                    value={formData.time_condition}
                    onChange={(e) => setFormData({ ...formData, time_condition: e.target.value })}
                  >
                    <option value="">Sin condición</option>
                    <option value="horario_oficina">Horario de Oficina</option>
                    <option value="fin_semana">Fin de Semana</option>
                    <option value="festivos">Festivos</option>
                  </select>
                </div>
              </div>

              <div className="form-actions">
                <button type="button" className="btn-secondary" onClick={resetForm}>
                  Cancelar
                </button>
                <button type="submit" className="btn-primary" disabled={createMutation.isPending || updateMutation.isPending}>
                  {editingId 
                    ? (updateMutation.isPending ? 'Actualizando...' : 'Actualizar Ruta')
                    : (createMutation.isPending ? 'Creando...' : 'Crear Ruta')
                  }
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

export default InboundRoutes

// frontend/pages/inbound-routes/index.vue
<template>
  <div class="space-y-6">
    <div class="flex justify-between items-center">
      <h1 class="text-3xl font-bold">Rutas Entrantes (DIDs)</h1>
      <div class="flex gap-2">
        <UButton
          v-if="error"
          icon="i-heroicons-arrow-path"
          @click="loadRoutes"
          :loading="loading"
        >
          Reintentar
        </UButton>
        <UButton
          icon="i-heroicons-plus"
          color="primary"
          @click="openCreateModal"
          :disabled="loading"
        >
          Agregar Ruta
        </UButton>
      </div>
    </div>

    <!-- Estado de carga/error -->
    <UAlert v-if="error" color="red" icon="i-heroicons-exclamation-triangle">
      {{ error }}
    </UAlert>

    <UCard v-if="loading" class="flex justify-center items-center py-12">
      <div class="text-center space-y-2">
        <UIcon name="i-heroicons-arrow-path" class="w-8 h-8 animate-spin mx-auto" />
        <p class="text-gray-500">Cargando rutas entrantes...</p>
      </div>
    </UCard>

    <!-- Filtros -->
    <UCard v-if="!loading" class="divide-y">
      <template #header>
        <div class="flex gap-2">
          <UInput
            v-model="searchQuery"
            placeholder="Buscar por DID o descripción..."
            icon="i-heroicons-magnifying-glass"
          />
          <USelect
            v-model="statusFilter"
            :options="[
              { label: 'Todas', value: null },
              { label: 'Activas', value: true },
              { label: 'Inactivas', value: false }
            ]"
            option-attribute="label"
            value-attribute="value"
            placeholder="Filtrar por estado"
          />
        </div>
      </template>

      <!-- Tabla -->
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-gray-50 dark:bg-gray-900">
            <tr>
              <th class="px-4 py-3 text-left font-semibold">DID</th>
              <th class="px-4 py-3 text-left font-semibold">Descripción</th>
              <th class="px-4 py-3 text-left font-semibold">Tipo Destino</th>
              <th class="px-4 py-3 text-left font-semibold">Destino</th>
              <th class="px-4 py-3 text-left font-semibold">Prioridad</th>
              <th class="px-4 py-3 text-left font-semibold">Estado</th>
              <th class="px-4 py-3 text-center font-semibold">Acciones</th>
            </tr>
          </thead>
          <tbody class="divide-y">
            <tr v-for="route in filteredRoutes" :key="route.id" class="hover:bg-gray-50 dark:hover:bg-gray-800">
              <td class="px-4 py-3 font-mono font-semibold">{{ route.did }}</td>
              <td class="px-4 py-3">{{ route.description }}</td>
              <td class="px-4 py-3">
                <UBadge color="blue" variant="subtle">{{ getDestinationTypeLabel(route.destination_type) }}</UBadge>
              </td>
              <td class="px-4 py-3">{{ route.destination }}</td>
              <td class="px-4 py-3">{{ route.priority }}</td>
              <td class="px-4 py-3">
                <UBadge :color="route.is_active ? 'green' : 'gray'" variant="subtle">
                  {{ route.is_active ? 'Activa' : 'Inactiva' }}
                </UBadge>
              </td>
              <td class="px-4 py-3 text-center">
                <UButton
                  variant="ghost"
                  icon="i-heroicons-pencil"
                  size="sm"
                  @click="editRoute(route)"
                />
                <UButton
                  variant="ghost"
                  icon="i-heroicons-trash"
                  color="red"
                  size="sm"
                  @click="deleteRoute(route.id)"
                />
              </td>
            </tr>
            <tr v-if="filteredRoutes.length === 0 && !loading">
              <td colspan="7" class="px-4 py-8 text-center text-gray-500">
                No hay rutas entrantes configuradas
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </UCard>

    <!-- Modal crear/editar -->
    <USlideover v-model="isModalOpen" title="Ruta Entrante" @close="resetForm">
      <div class="p-4 space-y-4">
        <UFormGroup label="DID/Número" help="Número telefónico entrante">
          <UInput v-model="form.did" placeholder="Ej: +573001234567" />
        </UFormGroup>

        <UFormGroup label="Descripción" help="Descripción de la ruta">
          <UInput v-model="form.description" placeholder="Ej: DID principal" />
        </UFormGroup>

        <UFormGroup label="Tipo de Destino">
          <USelect
            v-model="form.destination_type"
            :options="destinationTypes"
            option-attribute="label"
            value-attribute="value"
          />
        </UFormGroup>

        <UFormGroup label="Destino" help="Extensión, cola, IVR, etc.">
          <UInput v-model="form.destination" placeholder="Ej: 100" />
        </UFormGroup>

        <UFormGroup label="Prioridad">
          <UInput v-model.number="form.priority" type="number" min="1" />
        </UFormGroup>

        <UFormGroup label="Condición Horario (Opcional)">
          <UInput v-model="form.time_condition" placeholder="Ej: business_hours" />
        </UFormGroup>

        <UFormGroup>
          <UCheckbox v-model="form.is_active" label="Activada" />
        </UFormGroup>

        <div class="flex gap-2 pt-4">
          <UButton color="primary" @click="saveRoute" :loading="isSaving">
            Guardar
          </UButton>
          <UButton color="gray" @click="isModalOpen = false">
            Cancelar
          </UButton>
        </div>
      </div>
    </USlideover>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

interface InboundRoute {
  id: number
  did: string
  description: string
  destination_type: string
  destination: string
  priority: number
  time_condition?: string
  is_active: boolean
}

const destinationTypes = [
  { label: 'IVR', value: 'ivr' },
  { label: 'Cola', value: 'queue' },
  { label: 'Extensión', value: 'extension' },
  { label: 'Buzón de Voz', value: 'voicemail' },
  { label: 'Anuncio', value: 'announcement' }
]

const routes = ref<InboundRoute[]>([])
const loading = ref(false)
const error = ref<string | null>(null)
const searchQuery = ref('')
const statusFilter = ref<boolean | null>(null)
const isModalOpen = ref(false)
const isSaving = ref(false)
const editingId = ref<number | null>(null)

const { apiFetch } = useApi()

const form = ref({
  did: '',
  description: '',
  destination_type: 'queue',
  destination: '',
  priority: 1,
  time_condition: '',
  is_active: true
})

const filteredRoutes = computed(() => {
  return routes.value.filter(route => {
    const matchesSearch =
      route.did.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      route.description.toLowerCase().includes(searchQuery.value.toLowerCase())
    const matchesStatus = statusFilter.value === null || route.is_active === statusFilter.value
    return matchesSearch && matchesStatus
  })
})

const openCreateModal = () => {
  resetForm()
  isModalOpen.value = true
}

const editRoute = (route: InboundRoute) => {
  form.value = { ...route }
  editingId.value = route.id
  isModalOpen.value = true
}

const saveRoute = async () => {
  isSaving.value = true
  error.value = null
  try {
    if (editingId.value) {
      const { error: saveError } = await apiFetch(`/telephony/inbound-routes/${editingId.value}/`, {
        method: 'PUT',
        body: form.value
      })
      if (saveError.value) throw new Error('Error al guardar la ruta')
    } else {
      const { error: saveError } = await apiFetch('/telephony/inbound-routes/', {
        method: 'POST',
        body: form.value
      })
      if (saveError.value) throw new Error('Error al guardar la ruta')
    }
    await loadRoutes()
    isModalOpen.value = false
  } catch (err) {
    error.value = 'Error al guardar la ruta'
    console.error('Error saving route:', err)
  } finally {
    isSaving.value = false
  }
}

const deleteRoute = async (id: number) => {
  if (confirm('¿Estás seguro de que deseas eliminar esta ruta?')) {
    try {
      const { error: delError } = await apiFetch(`/telephony/inbound-routes/${id}/`, { method: 'DELETE' })
      if (delError.value) throw new Error('Error al eliminar la ruta')
      await loadRoutes()
    } catch (err) {
      error.value = 'Error al eliminar la ruta'
      console.error('Error deleting route:', err)
    }
  }
}

const loadRoutes = async () => {
  loading.value = true
  error.value = null
  const { data, error: fetchError } = await apiFetch<any>('/telephony/inbound-routes/')
  if (fetchError.value) {
    error.value = 'Error al cargar las rutas entrantes'
    console.error('Error loading inbound routes:', fetchError.value)
  } else {
    const raw = data.value
    routes.value = Array.isArray(raw) ? raw : (raw?.results || [])
  }
  loading.value = false
}

const resetForm = () => {
  form.value = {
    did: '',
    description: '',
    destination_type: 'queue',
    destination: '',
    priority: 1,
    time_condition: '',
    is_active: true
  }
  editingId.value = null
}

onMounted(() => loadRoutes())

const getDestinationTypeLabel = (type: string) => {
  return destinationTypes.find(t => t.value === type)?.label || type
}
</script>
